
server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/porteiro?sslmode=require
    username: porteiro-eletronico
    password: porteiro-eletronico