
server:
  port: 8080
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:${DB_URL:postgresql://porteiro.postgres.database.azure.com:5432/porteiro}
    username: ${DB_USERNAME:porteiroadm}
    password: ${DB_PASSWORD:DB090623!@}

porteiro:
  app:
    jwtSecret: vAavT+sW/M4qnHD0k6coA//g4gslN8qL9i0VFq6ZBsqxd3yDtRKtQQkM8WzpNQabbSBI5suzxweO4ZR2VG8mGg==
    jwtExpirationMs: 86400000
